### ISSUE TITLE
Copy/Paste of sfx doesn't work and you can't run game (with play button at the top).

### ISSUE THREAD

**Issue by dagondev** [PixelVision8/GameCreator#10]
Just like title says.

**Comment by PixelVision8** [comment]
Somewhere along the line, I broke the SFX tool during the last refactor. I'll look into these issues:

[ ] Fix copy button
[ ] Fix paste button
[ ] Play button is broken in nav.

**Comment by PixelVision8** [comment]
This has been fixed.
