### ISSUE TITLE
Persistent data path and new workspace location [0.7.4a]

### ISSUE THREAD

**Issue by AndyGFX** [PixelVision8/GameCreator#122]
Hi,

I found a few bugs.

1) probably you have unset Company Name in Build player properties => path to workspace i now on other place 

current:
AppData\LocalLow\DefaultCompany\Game Creator Pro\

previous:
AppData\LocalLow\Pixel Vision 8\Game Creator Pro\

2) manual paste new workspace path don't clear previous path if is longer as new one.

Best Regards,
AndyGFX

**Comment by PixelVision8** [comment]
Reopening this because I didn't catch the earlier issue that it is now using DefaultCompany as the base path.

**Comment by PixelVision8** [comment]
This has been fixed in v0.7.5 but will not be available until the v0.7.6 release.
