### ISSUE TITLE
Mouse release over tool icon after drag causes tool to load

### ISSUE THREAD

**Issue by christiancoler** [PixelVision8/GameCreator#181]
windows 10/v0.7.4

Noticing that after clicking and dragging (for example, moving around in the tilemap editor), if cursor is over an icon upon release, the tool will be inadvertently loaded

**Comment by PixelVision8** [comment]
This will be fixed in the next release. The new UI framework supports mouse focus on buttons so rolling off of them when the mouse is down doesn't trigger a different button. Works for scrollbars too.
