### ISSUE TITLE
Game Creator not responding for few secs. after going into/restarting the game

### ISSUE THREAD

**Issue by dagondev** [PixelVision8/GameCreator#23]
To clarify title, I mean I am waiting longer when starting or restarting game and GC freezes for few seconds at first.
Started a while ago and looks like it is related to some of my code changes although I can't put my finger on what caused it. My first guess it is related to amount of code I have in other lua files I load at start (from Lib folder).
I separated my code recently I have now 8 LoadScript calls with varying size of code in each file. 

I don't want to upload my project here, but I messaged link to project in email.

**Comment by PixelVision8** [comment]
The importer is not optimized so you may be seeing slowdowns on the .png parsing side of things. Do you have a lot of sprites or tiles in the tilemap? Also, 8 lua scripts is a lot, I've not tested games with large scripts outside of the tools but even so the string parse should be very fast.

**Comment by dagondev** [comment]
I resized my tilemap from 128x128 to 32x30 which is all I need, for now. And freezing is gone.

As I said earlier in mail, I found out that freezing stopped when I deleted tilemap-flags.png.
And before I had something like 256x256 and then resized to 128x128. I also forgot (only found out now) that while I have 128x128 tilemap and tilemap-flags, in data.json I have 64x64 size, so maybe it is the reason of freezing?

**Comment by PixelVision8** [comment]
Good to know. I think there are some issues around unfinished code where I wanted systems to limit the tilemap size based on the template but got distracted and move onto something else. I'll file a separate bug around connecting back up the data.json tilemap size to the importer in case that was causing the hanging.

I'll go ahead and close this for now. Feel free to comment or file a more specific bug if you see an issue.
