### ISSUE TITLE
Changing the BG color in the tilemap tool doesn't save

### ISSUE THREAD

**Issue by PixelVision8** [PixelVision8/GameCreator#374]
This may not be updating the system json file. Need to look into why the tilemap doesn't save bg color changes.

**Comment by PixelVision8** [comment]
This was happening because of the tilemap.json file was there and it overwrite the bg color. Need to make sure we don't re-import that bg color or update the json file when making changes in the editor when a compressed file exists.

**Comment by jessefreeman** [comment]
This has been fixed.
