### ISSUE TITLE
Noticing issue with Boot tool and SpriteBuilder

### ISSUE THREAD

**Issue by PixelVision8** [PixelVision8/GameCreator#393]
For some reason, the bottom of the logo is being cut off from the sprite builder in the boot tool.

![image](https://user-images.githubusercontent.com/24598054/33668819-a509f290-da55-11e7-8f80-f7c39d9bfb4d.png)

**Comment by PixelVision8** [comment]
Fix this by hand but Sprite Builder needs to bee looked at.

**Comment by jessefreeman** [comment]
This has been fixed.
