### ISSUE TITLE
loading a game by double click (windows version)

### ISSUE THREAD

**Issue by allaze-eroler** [PixelVision8/GameCreator#394]
hello, 

I'm using Game Creator Pro v0.7.6a. on Windows 7 Pro 64bits. 

I think I know why it didn't properly load into sandbox folder, when I double click on the game of my choice (could be from system tab or my own games) it worked like it does, but when I use Ctrl+1 two time, I got that message.

"The 'Workspace/Sandbox' directory is not valid. 
Press Ctrl+1 to launch the editor."

Here the pic:
![image](https://user-images.githubusercontent.com/6775478/33797636-f66fbdf0-dd0b-11e7-92ff-67cc5b96b499.png)

I found out that folder is empty even though I loaded the "game".
so, after some test with various different method, I haven't tried the "edit" button, which I tired it. This time, it worked and properly imported to sandbox folder!

here the result:
![image](https://user-images.githubusercontent.com/6775478/33797677-96e2f518-dd0c-11e7-8f58-85ff5e2eb348.png)

Hope it will help you.

**Comment by PixelVision8** [comment]
This is the new intended interaction, I just didn't get a chance to update the docs. You can now double-click on any game to play it but if you want to move it to the Sandbox folder you will need to click edit which makes a copy of it for you to work on.
