### ISSUE TITLE
The browser could not allocate enough memory for the WebGL content.

### ISSUE THREAD

**Issue by dagondev** [PixelVision8/GameCreator#40]
I exported my project to webgl. When I try to run it locally on firefox, I get alert "The browser could not allocate enough memory for the WebGL content. If you are the developer of this content, try allocating less memory to your WebGL build in the WebGL player settings."

Tried changing TOTAL_MEMORY value in Pixel Vision 8 Runner v0.7.2.json to be twice as big (as there is no single place giving information how much I use and how much I have, etc.) and that didn't help.

StreamingAssets/SampleLuaGame.pv8 have 109kb
Build/Pixel Vision 8 Runner v0.7.2.asm.code.unityweb have 3513kb 
Build/Pixel Vision 8 Runner v0.7.2.data.unityweb have 1720kb

**Comment by dagondev** [comment]
Any input on that? I would like to build my project: https://itch.io/t/118642/lockpicking-prototype#post-227173 and upload it on itch.io.
Should I optimize project to use less memory? If so any tips how to check how much I am above/what takes the most memory (any diagnostics?)?

**Comment by PixelVision8** [comment]
Sorry, didn't see this. I've seen Unity WebGL exports have issues around memory allocation. I can look into ways to fix that.

**Comment by dagondev** [comment]
No problem. You can always sort issues on no assignee to catch user created issues.

**Comment by PixelVision8** [comment]
I've allocated more memory to builds and need to test this out. Hope to have a fix for it in the next release.

**Comment by PixelVision8** [comment]
After looking into this I was able to add more memory to the WebGL build and run a more complex game demo. It looks like Advanced Builder isn't setting the memory correctly from the build preferences so I need to look into how to add this to the automated build process. Manually doing a build from Unity creates a working WebGL build.

**Comment by PixelVision8** [comment]
Modified the build script to include the following line for WebGL builds:

`PlayerSettings.SetPropertyString("emscriptenArgs", "-s ALLOW_MEMORY_GROWTH=1", BuildTargetGroup.WebGL);`

This will allow the Runner to expand its memory as needed but may cause performance problems. Since this is working, for now, I'll close this out and assess performance optimization later when I have more games to test with.
