### ISSUE TITLE
Linux build packed incorrectly

### ISSUE THREAD

**Issue by RamiLego4Game** [PixelVision8/GameCreator#503]
Hey jesse,

I have just found this problem when trying to run PV8 on Ubuntu,

Very simple, you have packed the build with the data folder named as `data`, while the executable refers to it as `Data`, so I easily fixed it by renaming it to `Data`.

I also found someone having the same problem but with more detailed post: https://itch.io/t/173125/failed-to-load-mono-on-linux

**Comment by PixelVision8** [comment]
Interesting, on Windows, it works fine as "data" and thought I tested that. I can go back and try to manually fix that build.

**Comment by PixelVision8** [comment]
This has been fixed.
