### ISSUE TITLE
Can't switch to the `Code Editor` when in the `Debug Tool`

### ISSUE THREAD

**Issue by RamiLego4Game** [PixelVision8/GameCreator#505]
As the title says, go to the `debug tool`, and try to switch to the `code editor`

**Comment by RamiLego4Game** [comment]
The `code editor` button is also drawn wrong:
![image](https://user-images.githubusercontent.com/6272475/33886865-9ed656f2-df50-11e7-8152-2e9242c740d0.png)
Unlike other places:
![image](https://user-images.githubusercontent.com/6272475/33886901-b07c0064-df50-11e7-8db7-e609f5ae2f49.png)

**Comment by PixelVision8** [comment]
This has been fixed

![image](https://user-images.githubusercontent.com/24598054/34254149-c424511a-e618-11e7-8f93-847c574d00d5.png)
