### ISSUE TITLE
unable to enter in any tools (windows version)

### ISSUE THREAD

**Issue by allaze-eroler** [PixelVision8/GameCreator#561]
as soon as i finished installing the new version of game creator pro, i got my game running fine, when i use CTRL+1 to enter the tool, i got this

![image](https://user-images.githubusercontent.com/6775478/34301540-56166e2c-e72d-11e7-9284-9b876ec05ac9.png)

turn out that i can't go in any tools, of course, i tried to delete the whole workspace folder and the bios file excepted the games folder. turn out it's stuck on this

![image](https://user-images.githubusercontent.com/6775478/34301667-c5b76556-e72d-11e7-8dad-38a6992eff02.png)

so, i figured it might be an error in the window build....

i use windows 7 pro 64bits and the game engine is version 0.7.7a pro

**Comment by PixelVision8** [comment]
Can you please try re-open the game creator and when the error happens, go into the Workspace/tmp/log.txt file and see if it is throwing an error?

**Comment by allaze-eroler** [comment]
sure things! here the result:

```
£Debug Log Created 20171222185903720
¥UnauthorizedAccessException: Access to the path "C:\Program Files (x86)\Game Creator Pro\Game Creator Pro v0.7.7_Data\StreamingAssets\System\PixelVisionOS\Tools\SaveTool\saves.json" is denied.
```

apparently it seem the game engine can't access this... :|

**Comment by PixelVision8** [comment]
Ok, I know what that error is. I can have a fix for the next release. One thing you might one to try to and do is go into the path and see if there is a saves.json file there now with permissions you can't access and delete it. If that isn't the case, it may be a Windows 7 issue not giving the Game Creator permission to write to the application's directory. The other solution may be to try and run it as Admin. In the next build I'll simply check for permissions and if it doesn't have access it will just not save data. I haven't seen that on Mac, Linux or Win 10.

**Comment by allaze-eroler** [comment]
hummm interesting, i tried to do like you said and apparently, the only solution is to run as an admin and it worked... so before it, i tested almost everything like this :

i deleted the file saves.json, it didn't worked, i decided to delete everything i save my "roms" elsewhere then uninstall the app... after that, i reinstalled it like a fresh fish.... (or fresh policeman that came out from police comedy academy) didn't worked, so, i decided to try that run as admin and that is where it worked like a charm!

the only suspicion i had would be because that the old version worked fine since it doesn't need to run as an admin however, in the new version, it needed to be... i'm wondering if it wasn't because of one typo in your code source? we are humans after all.... ^^;

**Comment by PixelVision8** [comment]
The reason for the change is that the new save mechanic will write data back to the source of where the game is loaded from. In the case of the built-in tools, these are now part of Game Creator exe itself. Since that is located in a protected directory, you are running into the error. I'll add some logic to saving that doesn't crash the tool but still allows you to work with tools but they will just not save their last state unless you chose to run it in admin mode. That being said, saving to games in your workspace should be fine since that is automatically placed in a non-protected storage location on your computer.

**Comment by PixelVision8** [comment]
Added a catch to saving game files which should now rout any errors to the log. This won't fix running the Game Creator in Admin mode on older versions of windows but it should stop the Game Creator from locking up.
