### ISSUE TITLE
DrawSprites draws sprites at bad position if you ScrollPosition over Y (over X works fine)

### ISSUE THREAD

**Issue by dagondev** [PixelVision8/GameCreator#8]
Hi, so title says all.

I have simple camera system in place that is based on player position in the world.

Camera position is set like this:
```

    function Init()
        glCamera.xPlayerOffset=glScreenPixelWidth/2
        glCamera.yPlayerOffset=glScreenPixelHeight/2
[...]
    function Update()
        glCamera.x=math.max(0,math.min(glPlayer.x-glCamera.xPlayerOffset,
            glTilemapPixelWidth))
        glCamera.y=math.max(0,math.min(glPlayer.y-glCamera.yPlayerOffset,
            glTilemapPixelHeight))  
```

It makes sure that screen is always centered on player unless we hit bounds of map (0,0 or tilemap size).
I am scrolling stuff with ScrollPosition() and this is my order of calling stuff:

```
function Draw()
    Clear()
    ScrollPosition(glCamera.x,glCamera.y)
    DrawTilemap()
    DrawObjects()
end
```

Where DrawObjects() iterates over dynamic objects in the game and draws them using DrawSprites().

If I move player only on X axis, everything works as expected, but if I moved player over Y axis (or both) dynamic objects, drawn with DrawSprites, are somehow scrolling with camera (but only over Y axis) - and I made sure that those objects doesn't change position.

**Comment by dagondev** [comment]
https://itch.io/t/96269/drawsprites-draws-sprites-at-bad-position-if-you-scrollposition-over-y-over-x-works-fine
From that thread you asked: 

> Also, are you adjusting for the scroll Y when you redraw the sprites? There may be a bug in DrawSprites(). I noticed that the mouse wasn't rendering correctly on the Music Tool's config screen which is shown by changing the scroll Y position. That logic could do with some more testing.

And I answered:

What you mean by adjusting? I don't think so.  I am only using ScrollPosition() as provided above and dynamic objects (that are drawn with DrawSprites()) have static x,y as they doesn't move (so far).

**Comment by PixelVision8** [comment]
I'll modify one of the demos to test for scrolling along the Y access to see how I can reproduce this. I think my original tests were all done on the X axis which may explain why I didn't pick up on this earlier.

**Comment by PixelVision8** [comment]
Here is an example of how this is breaking in the Tilemap Demo when enabling Y scrolling.

![tile-map-scroll-test-1](https://user-images.githubusercontent.com/24598054/28549792-aaab655e-70aa-11e7-9009-0dce83599814.gif)

**Comment by PixelVision8** [comment]
I've rebuilt the DrawSprites() method and TilemapDemo to account for scrolling on the x and y axis at the same time. This should fix this issue and a number of other bugs related to DrawSprites() not working correctly.

![tile-map-scroll-test-2](https://user-images.githubusercontent.com/24598054/28573063-4ae24706-7117-11e7-9bff-daf7c655f2b1.gif)
