### ISSUE TITLE
Tileflag 15 is recognised as 14

### ISSUE THREAD

**Issue by dagondev** [PixelVision8/GameCreator#9]
https://itch.io/t/79568/tileflag-15-is-recognised-as-14

I created flags with this spritesheet: https://www.dropbox.com/s/b0yxwz2jbt2z3q3/collisionflags.png?dl=0

I use this spritesheet as tiles in Tiled and export as advised to tilemap-flags.png. For some reason, the brightest flag (which should be 15) is read as 14.

Rest works as intended (although I am using 0 to 4 so far)

This is my tilemap-flags.png: https://www.dropbox.com/s/g84yjy62gaitgze/tilemap-flags.png?dl=0

**Comment by jessefreeman** [comment]
This is fixed.
